version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www/src
    ports:
      - "8080:80"
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - "8081:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      networks:
        - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
